use_frameworks!

target 'ModuleB_Example' do
  pod 'ModuleB', :path => '../'

  target 'ModuleB_Tests' do
    inherit! :search_paths

    pod 'SnapKit'
    pod 'Alamofire'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'ModuleC', :path => '../../ModuleC'
  end
end
