# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/guangqiang-liu/GQSpec.git'
source 'https://github.com/songmh2010/TDKit-Component.git'


target 'TDKit-Main' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #pod 'ModuleA', :path => '../ModuleA/ModuleA.podspec'
  #pod 'ModuleB', :path => '../ModuleB/ModuleB.podspec'

  pod 'ModuleA'
  #pod 'ModuleB'
  
  pod 'SnapKit'
  pod 'Alamofire'

end
